# Unit 4: Orthogonality, Projections, and Least Squares

In this unit:
1. Orthogonal and orthonormal vectors
1. Orthogonal vector spaces and relations for the fundamental subspaces
1. Grahm-Schmidt
1. QR factorization.
1. Projections
1. Least Squares

In [807]:
using LinearAlgebra
A = rand(1:20,5,5)
A = (A+A')/2

5×5 Array{Float64,2}:
  1.0   9.0  12.0  14.5  12.5
  9.0  10.0  11.0  10.5  12.0
 12.0  11.0  13.0  12.5  15.5
 14.5  10.5  12.5   1.0   9.5
 12.5  12.0  15.5   9.5  15.0

In [808]:
ev = reverse(eigvals(A))

5-element Array{Float64,1}:
  56.52528318030242
   1.0848697059837762
  -0.07654281905634898
  -3.619192999395491
 -13.91441706783433

In [809]:
At = copy(A);

In [838]:
Q, R = qr(At)
At = R*Q

5×5 Array{Float64,2}:
 56.5253         1.72512e-14   6.04835e-15   1.73952e-14  -2.162e-15
 -2.75403e-16  -13.9144       -1.00083e-14  -1.25402e-15  -6.97283e-15
 -1.95309e-33   -1.47281e-16  -3.61919      -1.53968e-14   2.25135e-15
 -8.55877e-48   -5.91068e-31  -1.50619e-14   1.08487      -3.50641e-15
  3.37329e-82    8.97135e-66   1.59244e-48  -4.19187e-34  -0.0765428

In [839]:
Q,R = qr(A)

LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
5×5 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.0410824   0.927153   -0.156958   -0.211284  -0.26348
 -0.369742    0.21748     0.767344   -0.119274   0.461466
 -0.492989    0.0228927   0.162816    0.695004  -0.496888
 -0.595695   -0.291882   -0.0886033  -0.649806  -0.360353
 -0.51353     0.0858475  -0.593454    0.189351   0.583845
R factor:
5×5 Array{Float64,2}:
 -24.3413  -21.9072   -26.3749  -16.1146   -25.9538
   0.0       8.73642   11.4978   16.5371    13.0689
   0.0       0.0       -1.6322    2.08999    0.0262457
   0.0       0.0        0.0       5.52059    3.36734
   0.0       0.0        0.0       0.0       -0.123358

In [848]:
sum(det.([rand([1,2,3,4,5,6,6],3,3) for _ in 1:10^6]) .== 0)

48199

In [844]:
det.([rand([1,2,3,4,5,6,6],3,3) for _ in 1:100])

100-element Array{Float64,1}:
 -90.0
   0.0
  -5.999999999999998
  19.0
 -23.0
  70.0
   0.0
 -80.0
  64.0
 -12.0
 102.0
 -52.0
 -20.000000000000004
   ⋮
   5.999999999999994
 -15.0
 -42.0
 102.0
 -26.000000000000007
  -8.000000000000004
 -25.000000000000004
   0.0
 -45.0
 -33.0
 108.99999999999999
  16.000000000000004

In [900]:
ℓ1 = 24; ℓ2=7; ℓ3 = -1;
ranks = [0,0,0,0] 
for _ in 1:10^5
    r = rank(rand([ℓ1,ℓ2,ℓ3],4,4))
#     push!(ranks,r)
    ranks[r] +=1
end
ranks

4-element Array{Int64,1}:
     0
   230
 15037
 84733

In [902]:
x = ones(5)
x[1:0]

0-element Array{Float64,1}

In [903]:
dot(x[1:0],x[1:0])

0.0

In [906]:
x = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [905]:
A = [2 3 ; 4 5; 6 8]

3×2 Array{Int64,2}:
 2  3
 4  5
 6  8

In [908]:
A*x'

DimensionMismatch: DimensionMismatch("matrix A has dimensions (3,2), matrix B has dimensions (3,1)")

In [909]:
x'

3×1 Adjoint{Int64,Array{Int64,2}}:
 1
 2
 3

In [911]:
x' === [1,2,3]

false