# Unit 2: Linear Equations and Elimination

In this unit:
1. Linear equations
1. Gaussian elimination
1. Pivots
1. Rank
1. LU factorization
1. Taylor series expansions with Jacobians

### Linear Equations

$$
\begin{array}{rcl}
x - 2y &=& 1\\
3x + 2y &=& 11
\end{array}
$$

or
$$
\begin{bmatrix}
1 & -2 \\
3 & 2
\end{bmatrix}
\begin{bmatrix}
x \\
y
\end{bmatrix}
=
\begin{bmatrix}
1 \\
11
\end{bmatrix}
$$

Multiply first equation by $3$ and subtract from second equation:

$$
\begin{array}{rcl}
x - 2y &=& 1\\
 y &=& 8
\end{array}
$$

or
$$
\begin{bmatrix}
1 & -2 \\
0 & 8
\end{bmatrix}
\begin{bmatrix}
x \\
y
\end{bmatrix}
=
\begin{bmatrix}
1 \\
8
\end{bmatrix}
$$

Now $y=8$ and from this we can find $x$

In [56]:
A = [1 -2; 3 2]; b=[1,11];

In [57]:
A2 = copy(A)
A2[2,:] = A[2,:] - 3A[1,:];
A2

2×2 Array{Int64,2}:
 1  -2
 0   8

In [47]:
using Pkg
Pkg.add("RowEchelon")

  Resolving package versions...
   Updating `~/Project.toml`
 [no changes]
   Updating `~/Manifest.toml`
 [no changes]


In [61]:
using RowEchelon

In [62]:
? rref

search: rref rref! rref_with_pivots rref_with_pivots! searchsortedfirst



```
rref(A)
```

Compute the reduced row echelon form of the matrix A. Since this algorithm is sensitive to numerical imprecision,

  * Complex numbers are converted to ComplexF64
  * Integer, Float16 and Float32 numbers are converted to Float64
  * Rational are kept unchanged

```jldoctest
julia> rref([ 1  2 -1  -4;
              2  3 -1 -11;
             -2  0 -3  22])
3×4 Array{Float64,2}:
 1.0  0.0  0.0  -8.0
 0.0  1.0  0.0   1.0
 0.0  0.0  1.0  -2.0

julia> rref([16  2  3  13;
              5 11 10   8;
              9  7  6  12;
              4 14 15   1])
4×4 Array{Float64,2}:
 1.0  0.0  0.0   1.0
 0.0  1.0  0.0   3.0
 0.0  0.0  1.0  -3.0
 0.0  0.0  0.0   0.0

julia> rref([ 1  2  0   3;
              2  4  0   7])
2×4 Array{Float64,2}:
 1.0  2.0  0.0  0.0
 0.0  0.0  0.0  1.0
```


In [64]:
[A I]

2×4 Array{Int64,2}:
 1  -2  1  0
 3   2  0  1

In [65]:
rref([A I])

2×4 Array{Float64,2}:
 1.0  0.0   0.25   0.25
 0.0  1.0  -0.375  0.125

In [66]:
inv(A)

2×2 Array{Float64,2}:
  0.25   0.25
 -0.375  0.125

In [63]:
A

2×2 Array{Int64,2}:
 1  2
 3  4